name: Generate Coverage

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
    cancel-in-progress: true

on:
    push:
        branches:
            - main
    workflow_dispatch:
    pull_request:
        branches:
            - main

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install cloudflared
              run: ./.github/scripts/install-cloudflared.sh

            - name: Load SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
                  known_hosts: ${{ secrets.VPS_SSH_KNOWN_HOSTS }}

            - name: Tunnel to VPS
              env:
                  TUNNEL_SERVICE_TOKEN_ID: ${{ secrets.CF_GHA_CLIENT_ID }}
                  TUNNEL_SERVICE_TOKEN_SECRET: ${{ secrets.CF_GHA_CLIENT_SECRET }}
              run: |
                  ssh -N -L 5432:localhost:5432 -o ProxyCommand="cloudflared access ssh --hostname %h" root@ssh.raidhub.io &

            - name: Run Tests
              env:
                  DATABASE_URL: postgresql://readonly:${{ secrets.POSTGRES_READONLY_PASSWORD }}@localhost:5432/raidhub?schema=public&connection_limit=5&pool_timeout=60
              run: |
                  yarn && yarn prisma generate
                  yarn test --coverage --coverageReporters=lcov --coverageReporters=html --bail=false
              continue-on-error: true

            - name: Upload coverage reports
              uses: actions/upload-artifact@v4
              with:
                  name: test-coverage.info
                  path: ./coverage/lcov.info
                  if-no-files-found: error
