name: Create migration file

on:
    push:
        branches:
            - "main"
            - "ci"
jobs:
    create:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install cloudflared
              run: ./.github/scripts/install-cloudflared.sh

            - name: Load SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
                  known_hosts: ${{ secrets.VPS_SSH_KNOWN_HOSTS }}

            - name: Install dependencies
              run: yarn install

            - name: Connect to prod database
              env:
                  TUNNEL_SERVICE_TOKEN_ID: ${{ secrets.CF_GHA_CLIENT_ID }}
                  TUNNEL_SERVICE_TOKEN_SECRET: ${{ secrets.CF_GHA_CLIENT_SECRET }}
              run: |
                  ssh -N -L 5433:localhost:5432 -o ProxyCommand="cloudflared access ssh --hostname %h" root@ssh.raidhub.io &

            - name: Spin up shadow database
              env:
                  POSTGRES_DB: raidhub
                  POSTGRES_USER: readonly
                  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_READONLY_PASSWORD }}
                  POSTGRES_PORT: 5432
              run: docker-compose -f docker-compose.yml up -d

            - name: Calculate diff
              run: |
                  yarn prisma migrate diff --script \
                    --shadow-database-url "postgresql://readonly:${{ secrets.POSTGRES_READONLY_PASSWORD }}@localhost:5432/raidhub?schema=public" \
                    --from-url postgresql://readonly:${{ secrets.POSTGRES_READONLY_PASSWORD }}@localhost:5433/raidhub?schema=public \
                    --to-migrations ./prisma/migrations > migration.sql

            - name: Upload migration file
              uses: actions/upload-artifact@v3
              with:
                  name: migration-sql
                  path: migration.sql
