name: Create migration file

on:
    push:
        branches:
            - "main"
jobs:
    create:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:13
                env:
                    POSTGRES_DB: raidhub
                    POSTGRES_USER: username
                    POSTGRES_PASSWORD: password
                ports:
                    - 5432:5432
                options: --health-cmd "pg_isready -U username" --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install cloudflared
              run: ./.github/scripts/install-cloudflared.sh

            - name: Load SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
                  known_hosts: ${{ secrets.VPS_SSH_KNOWN_HOSTS }}

            - name: Install dependencies
              run: yarn install

            - name: Connect to prod database
              env:
                  TUNNEL_SERVICE_TOKEN_ID: ${{ secrets.CF_GHA_CLIENT_ID }}
                  TUNNEL_SERVICE_TOKEN_SECRET: ${{ secrets.CF_GHA_CLIENT_SECRET }}
              run: |
                  ssh -N -L 5433:localhost:5432 -o ProxyCommand="cloudflared access ssh --hostname %h" root@ssh.raidhub.io &

            - name: Calculate diff
              run: |
                  yarn prisma migrate diff --script \
                    --shadow-database-url "postgresql://username:password@localhost:5432/raidhub?schema=public" \
                    --from-url postgresql://readonly:${{ secrets.POSTGRES_READONLY_PASSWORD }}@localhost:5433/raidhub?schema=public \
                    --to-migrations ./prisma/migrations > migration.sql

            - name: Upload migration file
              uses: actions/upload-artifact@v3
              with:
                  name: migration-sql
                  path: migration.sql
