name: Lint checks

on:
    push:
        branches:
            - "*"
            - "!main"
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Lint
              run: |
                  yarn
                  yarn lint
