name: Lint checks

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
    cancel-in-progress: true

on:
    pull_request:
        branches:
            - main
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1

            - name: Lint
              run: |
                  yarn
                  yarn lint
                  yarn format --check
