name: Migration check

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
    cancel-in-progress: true

on:
    pull_request:
        branches:
            - main
jobs:
    diff:
        runs-on: ubuntu-latest
        env:
            POSTGRES_DB: raidhub
            POSTGRES_PORT: 5432
            POSTGRES_USER: readonly
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_READONLY_PASSWORD }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: yarn

            - name: Spin up shadow database
              run: docker-compose -f docker-compose.yml up -d

            - name: Calculate diff
              run: |
                  yarn prisma migrate diff --exit-code \
                    --shadow-database-url "postgresql://readonly:${{ secrets.POSTGRES_READONLY_PASSWORD }}@localhost:5432/raidhub?schema=public" \
                    --from-schema-datamodel ./prisma/schema.prisma \
                    --to-migrations ./prisma/migrations
