name: Deploy Staging API

on:
    workflow_dispatch:
    push:
        branches:
            - add-more-types

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install cloudflared
              run: ./.github/scripts/install-cloudflared.sh

            - name: Load SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
                  known_hosts: ${{ secrets.VPS_SSH_KNOWN_HOSTS }}

            - name: Deploy API
              env:
                  TUNNEL_SERVICE_TOKEN_ID: ${{ secrets.CF_GHA_CLIENT_ID }}
                  TUNNEL_SERVICE_TOKEN_SECRET: ${{ secrets.CF_GHA_CLIENT_SECRET }}
              run: |
                  branch_name="${{ github.ref }}#refs/heads/"
                  ssh -o ProxyCommand="cloudflared access ssh --hostname %h" root@ssh.raidhub.io "cd ../RaidHub/Staging-API && git fetch && git reset --hard origin/$branch_name && ./.github/scripts/deploy.sh \"raidhub-api-staging\""
