name: Manually Deploy API

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check if user is a repo admin
              working-directory: ./
              run: |
                  if [[ $(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission" | jq -r '.permission') != "admin" ]]; then
                  echo "Only repo admins can run this action."
                  exit 1
                  fi

            - name: SSH to VPS and Start API
              uses: appleboy/ssh-action@v0.1.9
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USERNAME }}
                  key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
                  port: 443
                  timeout: 120s
                  script: |
                      cd ~/../RaidHub/RaidHub-API/
                      git pull origin main
                      source ~/.nvm/nvm.sh
                      nvm use 20
                      yarn
                      yarn prisma generate
                      yarn build 
                      yarn start
