name: Typescript check

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
    cancel-in-progress: true

on:
    pull_request:
        branches:
            - main
jobs:
    types:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Types
              run: |
                  yarn
                  yarn types
